#!/usr/bin/env python3
"""Regenerate the A–Z section (and the headline count) of ``Term Index.md``
from the actual notes in ``Terms/``.

``Term Dashboard.base`` is the live source of truth; it counts every note whose
frontmatter has ``type: term``. This script keeps the hand-browsable
``Term Index`` in sync with that same rule, so the two can't silently drift.

Usage (from anywhere)::

    python tools/gen_term_index.py

It rewrites only the block between the "## A–Z (existing terms)" heading and the
"## Coverage roadmap (backlog)" heading, and updates the "**N terms**" count.
The curated backlog section is left untouched.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent  # the IT-Dictionary vault
TERMS = ROOT / "Terms"
INDEX = ROOT / "Term Index.md"

START = "## A–Z (existing terms)"
END = "## Coverage roadmap (backlog)"


def is_term(md: str) -> bool:
    """True if the note's YAML frontmatter declares ``type: term``."""
    m = re.match(r"^---\n(.*?)\n---", md, re.S)
    if not m:
        return False
    return re.search(r'^type:\s*"?term"?\s*$', m.group(1), re.M) is not None


def main() -> int:
    titles = [
        p.stem
        for p in TERMS.glob("*.md")
        if is_term(p.read_text(encoding="utf-8"))
    ]
    titles.sort(key=str.lower)

    groups: dict[str, list[str]] = {}
    for t in titles:
        first = t[0].upper()
        groups.setdefault(first if first.isalpha() else "#", []).append(t)

    block = [
        START,
        "",
        "*Generated by `tools/gen_term_index.py` — do not hand-edit. "
        "The live count is [[Term Dashboard]] (`type: term`).*",
        "",
    ]
    for key in sorted(groups):
        links = " · ".join(f"[[{t}]]" for t in groups[key])
        block += [f"**{key}** — {links}", ""]
    az = "\n".join(block).rstrip() + "\n\n"

    doc = INDEX.read_text(encoding="utf-8")
    i, j = doc.index(START), doc.index(END)
    doc = doc[:i] + az + doc[j:]
    doc = re.sub(r"\*\*\d[\d,]*\s+terms\*\*", f"**{len(titles)} terms**", doc, count=1)
    INDEX.write_text(doc, encoding="utf-8")

    print(f"Term Index rebuilt from {len(titles)} terms.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
